@estudiantes_icinf_HostAddress = http://localhost:5199

### Listar todos los estudiantes
GET {{estudiantes_icinf_HostAddress}}/api/estudiantes

### Obtener un estudiante por id
GET {{estudiantes_icinf_HostAddress}}/api/estudiantes/1

### Crear un estudiante
POST {{estudiantes_icinf_HostAddress}}/api/estudiantes
Content-Type: application/json

{
  "nombre": "Pedro",
  "apellido": "Diaz",
  "email": "pedro.diaz@alu.uct.cl",
  "carrera": "Ingenieria Civil Informatica"
}

### Actualizar un estudiante
PUT {{estudiantes_icinf_HostAddress}}/api/estudiantes/1
Content-Type: application/json

{
  "nombre": "Juan Actualizado",
  "apellido": "Perez",
  "email": "juan.perez@alu.uct.cl",
  "carrera": "Ingenieria Civil Informatica"
}

### Eliminar un estudiante
DELETE {{estudiantes_icinf_HostAddress}}/api/estudiantes/1
